<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Financial Integrated Applications - N_61d5e8</name>
   <tag></tag>
   <elementGuidId>e0e37ddc-f2fb-48ff-b0c2-33ce4bafb99f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-element.w-full.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8575c1a-4b68-4cf0-a5f5-90fdc53fe6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49955395-67c9-46bf-8e87-fca3c9544e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>43afb98c-2c56-4f63-b0c0-d68fa362f113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>72665e92-de51-45da-bcc0-f93004a3f898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element w-full ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8c965152-eace-44eb-8309-3b7d38d25119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/jhi-root[1]/jhi-logingw[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;background-login surface-ground h-screen w-screen flex align-items-center justify-content-center&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;surface-card py-7 px-5 sm:px-7 shadow-2 flex flex-column w-11 sm:w-30rem&quot;]/div[@class=&quot;login-form&quot;]/span[@class=&quot;p-input-icon-left mb-4&quot;]/input[@class=&quot;p-inputtext p-component p-element w-full ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>173a29e0-e3bb-424f-84a3-b40a832a0a05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>2623e96c-c80e-43b1-9404-f3cf3243f86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3afccf98-c3b8-4e3c-bf76-7ba10ec6f253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>49ffdbb1-38ac-4955-af2a-62da41ff0d69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
