<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Judul Kontrak_judulKontrak</name>
   <tag></tag>
   <elementGuidId>4e9f4e69-4b15-42a5-a0fd-8edc10e047bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#judulKontrak</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='judulKontrak']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>46ae83be-aa7d-4100-bfbf-2166915fcb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>judulKontrak</value>
      <webElementGuid>4b5c8ed1-0e52-4e09-aeef-fc355a87976d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>judulKontrak</value>
      <webElementGuid>e73600bb-cfa2-4963-88f4-678197cc7934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0fbdeec-a218-4ef8-a348-2676dba6f11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>bdc96f21-d972-4e62-8f5a-752c43b8af84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>7e3f5321-c2a7-4050-923f-463f2bfede34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;judulKontrak&quot;)</value>
      <webElementGuid>efd1b3f3-4794-4d8c-be80-089010832ade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='judulKontrak']</value>
      <webElementGuid>37e01324-7a45-4aee-a012-46361cd5900e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e45b0c51-d38e-45f8-adfc-1d6fea4a24b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'judulKontrak' and @type = 'text']</value>
      <webElementGuid>b18593ce-5391-4d07-9a85-0d82f652b946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
