<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Dokumen Post Kontrak</name>
   <tag></tag>
   <elementGuidId>5577bbf0-91b9-4df8-9f16-5e872f4436da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p-tabpanel-4-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='p-tabpanel-4-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7edd1e24-6b55-45e8-abd7-8d6220faa8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>993f4c80-278f-4216-9e51-b48bf79bd079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-ripple p-tabview-nav-link</value>
      <webElementGuid>644a8c14-bfe1-45b4-ab53-97d52e0ea2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-tabpanel-4-label</value>
      <webElementGuid>7bb8a149-247b-4a54-8057-053ae46d990e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>p-tabpanel-4</value>
      <webElementGuid>ccf09494-ddef-4db5-8ea4-91fd56208063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>91ac7015-144e-46bc-8f84-5a46bd5afe98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Dokumen Post Kontrak</value>
      <webElementGuid>6d93de28-d98a-4955-8705-3c61a7d9c9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-4-label&quot;)</value>
      <webElementGuid>f004a013-2c39-44d9-a4ef-67a619b14b37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='p-tabpanel-4-label']</value>
      <webElementGuid>cf44d8c4-3c23-4659-88d7-84f2b56b775c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Syarat Pembayaran'])[1]/following::a[1]</value>
      <webElementGuid>902f9eeb-f791-4ae1-9697-0c930f2665c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Direksi Pekerjaan'])[1]/following::a[2]</value>
      <webElementGuid>b99ddf1b-a253-4065-8728-3d4c743d653d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/preceding::a[1]</value>
      <webElementGuid>f26c54df-445f-47cc-b2cb-a41476159837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>89e0b258-2797-4dde-9c9e-f91869fa77ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'p-tabpanel-4-label' and (text() = 'Daftar Dokumen Post Kontrak' or . = 'Daftar Dokumen Post Kontrak')]</value>
      <webElementGuid>72a2e25f-b176-4875-8e29-7ef3916038ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
