<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Dokumen Post Kontrak</name>
   <tag></tag>
   <elementGuidId>826bc611-2b97-4454-bef3-250b1cd2a334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p-tabpanel-4-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='p-tabpanel-4-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19d1b3b3-8197-4466-8251-409c3ca72a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>67c512d1-1337-4bfc-97b1-92bb4c80bba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-ripple p-tabview-nav-link</value>
      <webElementGuid>db8bee7b-729e-4144-887c-b31d78a22a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-tabpanel-4-label</value>
      <webElementGuid>4a9a91a8-7185-4fe3-9bf7-75086bdb0773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>p-tabpanel-4</value>
      <webElementGuid>1cde14f5-4f8f-42b4-aa1f-779aadf64a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b70cf2a-546d-471d-a26a-afd0c9cafe12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Dokumen Post Kontrak</value>
      <webElementGuid>021d35bb-2478-42d6-ba58-346d0a88399c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-4-label&quot;)</value>
      <webElementGuid>1e8f82dd-c96e-47af-be93-30f6b48bbdfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='p-tabpanel-4-label']</value>
      <webElementGuid>7a9fa39d-58cf-4236-9e1b-66549fa3250c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Syarat Pembayaran'])[1]/following::a[1]</value>
      <webElementGuid>65078103-4851-40d7-aa71-82ac15ec66e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Direksi Pekerjaan'])[1]/following::a[2]</value>
      <webElementGuid>1cdcf435-1236-4758-b9d8-9ac23fb0ff76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/preceding::a[1]</value>
      <webElementGuid>e8f3495b-a231-41a3-b189-fb00daf30547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>9a0d7383-f0c7-443a-9a9e-22ea42f76e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'p-tabpanel-4-label' and (text() = 'Daftar Dokumen Post Kontrak' or . = 'Daftar Dokumen Post Kontrak')]</value>
      <webElementGuid>1d2a92dc-a5ab-45f6-aa05-26b28603dd06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
