<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_241A00 Pendapatan TL komponen A - Common</name>
   <tag></tag>
   <elementGuidId>89ba3dc8-c5e9-4f00-8faa-17fe1ca7566f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-0']/p-tree/div/div/ul/p-treenode/li/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-treenode-content.p-treenode-selectable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2cb9e945-f5ee-45ec-aa11-3bef2e945c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>2b3d7ca8-b567-4e0a-8cad-08b1ffb29866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-treenode-content p-treenode-selectable</value>
      <webElementGuid>fb51d077-c0a0-4487-b56a-a995166ac8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e47bd5e2-5b29-4259-bebd-3d4f9b11a1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c20ec219-27bd-4229-8d66-8383a3c323e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4e810a52-c0c9-473a-94b8-3fbd93e155e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e7cb0b82-9e06-4a2a-86b2-f91b0f844d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>241A00 Pendapatan TL komponen A - Common</value>
      <webElementGuid>60804ee1-34d2-4bd3-86c0-c8871ee8d161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>241A00 Pendapatan TL komponen A - Common</value>
      <webElementGuid>800aeddb-d4e9-4b06-9782-ebdbf46c10e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/p-tree[@class=&quot;p-element&quot;]/div[@class=&quot;ng-star-inserted p-tree p-component p-tree-selectable&quot;]/div[@class=&quot;p-tree-wrapper ng-star-inserted&quot;]/ul[@class=&quot;p-tree-container ng-star-inserted&quot;]/p-treenode[@class=&quot;p-element ng-star-inserted&quot;]/li[@class=&quot;p-treenode ng-star-inserted&quot;]/div[@class=&quot;p-treenode-content p-treenode-selectable&quot;]</value>
      <webElementGuid>32cd8532-56ac-4ded-b25a-691577f92935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-0']/p-tree/div/div/ul/p-treenode/li/div</value>
      <webElementGuid>032d0c93-5281-4fac-b1fb-6916a688b6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[1]/following::div[4]</value>
      <webElementGuid>f3314c5f-2eda-46ff-929a-d2e84018dd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distrik'])[1]/following::div[5]</value>
      <webElementGuid>4b02b235-dcf5-4fe3-b0d4-89c97d5d11cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distrik'])[2]/preceding::div[16]</value>
      <webElementGuid>9da3f794-08ba-4db4-aae0-e80cf82e50db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[2]/preceding::div[17]</value>
      <webElementGuid>0b8c042b-5061-4bf3-90a9-06c5295a17f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-treenode/li/div</value>
      <webElementGuid>400b5031-acd4-4f52-bede-9691f9cbe5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '241A00 Pendapatan TL komponen A - Common' or . = '241A00 Pendapatan TL komponen A - Common')]</value>
      <webElementGuid>7fc3d9bc-3194-48c2-8dd9-b9f4960463f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
