<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Harga Satuan_hrgSatuan</name>
   <tag></tag>
   <elementGuidId>4c686a1e-3186-4799-b63f-d8bd84635a21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hrgSatuan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hrgSatuan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8395e081-3f24-4dd2-b636-b54c31cf5318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>113bfec0-637c-47ea-a76c-ec7c10fd9b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputnumber-input</value>
      <webElementGuid>cbed375b-6f6b-46ad-8514-e7153ec23d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hrgSatuan</value>
      <webElementGuid>9eb345c7-371f-41eb-93e5-0d02cd4844ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hrgSatuan&quot;)</value>
      <webElementGuid>7ecf4dc7-8c05-4845-a5f7-860df2513136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hrgSatuan']</value>
      <webElementGuid>61efa2b5-fcbc-4bea-bc1b-de513ce19112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/p-inputnumber/span/input</value>
      <webElementGuid>2842a839-78ec-4fba-a1fc-97ddc31d9cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hrgSatuan']</value>
      <webElementGuid>f797a769-21e0-40a4-b68a-2d917b7fc2d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
