<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sa_p-ink p-ink-active</name>
   <tag></tag>
   <elementGuidId>46f15d2e-bf36-4aeb-8f5a-e8663ff5756d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td[5]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-ink.p-ink-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eaa76ea5-00eb-4d3d-8615-71487fc87348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ink p-ink-active</value>
      <webElementGuid>36b82851-7ca7-46cc-b760-8f009cd97a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c83-35 p-datepicker p-component ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c83-35 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c83-35 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c83-35 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c83-35&quot;]/tbody[@class=&quot;ng-tns-c83-35&quot;]/tr[@class=&quot;ng-tns-c83-35 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c83-35 p-datepicker-today ng-star-inserted&quot;]/span[@class=&quot;p-ripple p-element ng-tns-c83-35 ng-star-inserted&quot;]/span[@class=&quot;p-ink p-ink-active&quot;]</value>
      <webElementGuid>562c96de-b059-4f4c-bdb0-fadf97cff932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/span/span</value>
      <webElementGuid>dfd31ed8-197b-40d2-89b1-45238bf34bbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
