<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign In_p-ink p-ink-active</name>
   <tag></tag>
   <elementGuidId>75179c4b-3e9f-404c-a3b8-31037eae8947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-ink.p-ink-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1619b0f6-52a1-49c0-a314-d706d4b8ab6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ink p-ink-active</value>
      <webElementGuid>68966361-5d23-4f14-a3a0-646773a98659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/jhi-root[1]/jhi-logingw[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;background-login surface-ground h-screen w-screen flex align-items-center justify-content-center&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;surface-card py-7 px-5 sm:px-7 shadow-2 flex flex-column w-11 sm:w-30rem&quot;]/div[4]/button[@class=&quot;p-element p-ripple mb-4 flex justify-content-center p-button p-component&quot;]/span[@class=&quot;p-ink p-ink-active&quot;]</value>
      <webElementGuid>b9042181-48c7-4efe-99a1-493839bc426b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]</value>
      <webElementGuid>0d6d2ee0-0e83-4c4d-a9f6-e0d5a8478d65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
