<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes</name>
   <tag></tag>
   <elementGuidId>768b98cf-51f2-4d3b-b018-a0b9a347fe4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[38]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb5c6941-4a34-4694-b2bb-5b9fd3621073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c857bc85-faf0-4639-b770-aa7227f1fe97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>pi pi-check</value>
      <webElementGuid>54b6e7a0-bbef-4562-9a59-600998a0fb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>6bb71c47-460f-457c-beb8-5c717f6f833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-button-text p-button p-component ng-star-inserted</value>
      <webElementGuid>e8230f70-5be1-479e-94a4-c6137f458d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>92e47d64-d238-43b2-9492-755e9afc395e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-4&quot;)/jhi-payung-dokpostkontrak-listgw[1]/jhi-payung-dokpostkontrak-formgw[1]/p-dialog[@class=&quot;p-element ng-tns-c110-40 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-40 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c110-40 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-40 p-dialog-content&quot;]/jhi-docmeta-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card ng-star-inserted&quot;]/p-dialog[@class=&quot;p-element ng-tns-c110-66 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-66 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c110-66 p-dialog p-component p-dialog-draggable p-dialog-resizable ng-star-inserted&quot;]/div[@class=&quot;p-dialog-footer ng-tns-c110-66 ng-star-inserted&quot;]/button[@class=&quot;p-element p-button-text p-button p-component ng-star-inserted&quot;]</value>
      <webElementGuid>62eabc2f-930c-41bc-9b8a-33ee6846891a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[38]</value>
      <webElementGuid>d6a99959-0b46-40b6-aa54-5f3015ed2a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-4']/jhi-payung-dokpostkontrak-listgw/jhi-payung-dokpostkontrak-formgw/p-dialog/div/div/div[2]/jhi-docmeta-form/div/p-dialog/div/div/div[4]/button[2]</value>
      <webElementGuid>7290c99d-e2cf-42bd-b286-2e6381c2b87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/following::button[1]</value>
      <webElementGuid>1b5edd2a-779f-46fd-b50f-d5da8f2a9c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testing'])[3]/following::button[2]</value>
      <webElementGuid>4fc83be0-8cba-41dd-bcc3-caa51c3e78b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/preceding::button[1]</value>
      <webElementGuid>a16b26b2-787d-4748-8d02-1b7ea9970818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>4053f46e-a350-4b8e-b992-770822fbf2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>5c12464a-5389-4938-870e-fe7b373304e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
