<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_PAYMENT</name>
   <tag></tag>
   <elementGuidId>426da047-59ac-4e1e-966c-80bcc699b632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-6']/form/div/div[2]/p-multiselect/div/div[4]/div[2]/ul/p-multiselectitem[2]/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>bbc6caaa-3451-42c4-84fc-809806a899b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-multiselect-item</value>
      <webElementGuid>1632b641-dd22-45c1-be6e-98f4d49767be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>PAYMENT</value>
      <webElementGuid>1ba50e4c-74b2-40e7-a2c0-ee9756b8ffe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f7314c61-b0f3-4975-b7b9-ab3dbedb932e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAYMENT</value>
      <webElementGuid>2dac266b-87e8-4bd4-8e28-f459cfab117c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-6&quot;)/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;p-formgrid grid p-fluid&quot;]/div[@class=&quot;field col p-0 ml-1&quot;]/p-multiselect[@class=&quot;p-element p-inputwrapper p-multiselect-sm-custom-0 ng-tns-c117-64 ng-untouched ng-pristine ng-valid ng-star-inserted p-inputwrapper-focus&quot;]/div[@class=&quot;ng-tns-c117-64 p-multiselect p-component p-multiselect-open p-multiselect-chip&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c117-64 p-multiselect-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-multiselect-items-wrapper ng-tns-c117-64&quot;]/ul[@class=&quot;p-multiselect-items p-component ng-tns-c117-64 ng-star-inserted&quot;]/p-multiselectitem[@class=&quot;p-element ng-tns-c117-64 ng-star-inserted&quot;]/li[@class=&quot;p-ripple p-element p-multiselect-item&quot;]</value>
      <webElementGuid>155ebaa7-3d4c-4fc9-9656-1ae061ee8c2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-6']/form/div/div[2]/p-multiselect/div/div[4]/div[2]/ul/p-multiselectitem[2]/li</value>
      <webElementGuid>e1c69266-8182-40f3-afda-aa2acb3f5c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCMAP'])[1]/following::li[1]</value>
      <webElementGuid>73db0523-0251-4ddf-9f9c-113527f8bbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Akses'])[1]/following::li[2]</value>
      <webElementGuid>4d571a34-44ea-4e76-834b-9a277a20c4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAXES'])[1]/preceding::li[1]</value>
      <webElementGuid>2c62836f-a86f-4b06-bf9e-98ed59e69b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-multiselectitem[2]/li</value>
      <webElementGuid>bbbe0d61-149e-49a8-90c3-eb151e116530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'PAYMENT' or . = 'PAYMENT')]</value>
      <webElementGuid>4b137e72-4189-4d83-bff3-8fc0af87a9c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
