<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>17738862-6c02-4a2b-bc37-71d955ec11e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-element.p-button-sm.p-button-warning.mr-2.p-button.p-component</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_13']/div/div[2]/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b0f0cd1-6fab-4c2e-9113-212e281d5a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>6e5b3b62-d0c8-46f9-bfb9-bc1da9b4f924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>pi pi-pencil</value>
      <webElementGuid>1c834fea-cd92-4392-8019-eafc52e05e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-button-sm p-button-warning mr-2 p-button p-component</value>
      <webElementGuid>61b0414f-1749-4e34-a1ab-dfc2b511a87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fbe4ee2a-b996-419d-a84c-7fea33451728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>bcd3d5c8-f027-43a7-afcd-df2416cbf70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_13&quot;)/div[@class=&quot;p-datatable-header ng-star-inserted&quot;]/div[@class=&quot;flex justify-content-between ng-star-inserted&quot;]/div[@class=&quot;flex wrapper&quot;]/div[@class=&quot;text-center&quot;]/button[@class=&quot;p-element p-button-sm p-button-warning mr-2 p-button p-component&quot;]</value>
      <webElementGuid>74a185d6-afee-410e-a124-edeaa49a44fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_13']/div/div[2]/div/div[2]/button</value>
      <webElementGuid>d86651f5-c3ac-4475-8432-9c9c9a01af76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/following::button[1]</value>
      <webElementGuid>d967799f-f7a2-4d97-9386-12479753f95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Kontrak Payung'])[2]/following::button[2]</value>
      <webElementGuid>a4e6d602-7557-4168-b0db-4612b4b189d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::button[1]</value>
      <webElementGuid>ca6ca207-c690-478e-9746-c197eeaa3d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>9b63ea34-9ed9-480a-b9a5-8d5a2c37a08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>1369cc30-50e5-4cdf-94c6-f732204329aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
