<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_PAYMENT</name>
   <tag></tag>
   <elementGuidId>afaa9090-09e6-4e2e-bded-9922d09090ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-6']/form/div/div[2]/p-multiselect/div/div[4]/div[2]/ul/p-multiselectitem[2]/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2ec74225-a904-4a72-8eda-3df4851dd13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-multiselect-item</value>
      <webElementGuid>620066f5-0866-4a01-96d5-90179653ccac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>PAYMENT</value>
      <webElementGuid>d942d31b-0b94-4222-b703-83abe5f2a9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6c330d0e-c4d2-4fa5-ba85-c5d3576a7b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAYMENT</value>
      <webElementGuid>f220941d-390c-4b77-adaa-90b4f266f081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-6&quot;)/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;p-formgrid grid p-fluid&quot;]/div[@class=&quot;field col p-0 ml-1&quot;]/p-multiselect[@class=&quot;p-element p-inputwrapper p-multiselect-sm-custom-0 ng-tns-c117-64 ng-untouched ng-pristine ng-valid ng-star-inserted p-inputwrapper-focus&quot;]/div[@class=&quot;ng-tns-c117-64 p-multiselect p-component p-multiselect-open p-multiselect-chip&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c117-64 p-multiselect-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-multiselect-items-wrapper ng-tns-c117-64&quot;]/ul[@class=&quot;p-multiselect-items p-component ng-tns-c117-64 ng-star-inserted&quot;]/p-multiselectitem[@class=&quot;p-element ng-tns-c117-64 ng-star-inserted&quot;]/li[@class=&quot;p-ripple p-element p-multiselect-item&quot;]</value>
      <webElementGuid>a99f4752-d5ed-48ed-a719-0980b8fcea96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-6']/form/div/div[2]/p-multiselect/div/div[4]/div[2]/ul/p-multiselectitem[2]/li</value>
      <webElementGuid>33acab86-5177-4c21-8fb4-28a591ff9dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCMAP'])[1]/following::li[1]</value>
      <webElementGuid>b48752a8-fed1-4b69-809d-54afecec4dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Akses'])[1]/following::li[2]</value>
      <webElementGuid>dbc2e62d-5c7b-44ab-9042-068224d0936e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAXES'])[1]/preceding::li[1]</value>
      <webElementGuid>b4f4af5f-5cc0-408b-a0d9-62ae0c30eeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-multiselectitem[2]/li</value>
      <webElementGuid>89edc4ec-7f77-4346-b410-a88b3a741774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'PAYMENT' or . = 'PAYMENT')]</value>
      <webElementGuid>ee72e556-e3f5-4b45-ac82-05cf8f2c61e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
