<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_namaDok</name>
   <tag></tag>
   <elementGuidId>746d2ba1-adec-43d3-8f1a-e2204fa6a72b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namaDok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namaDok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2bf3109-c57e-405c-9223-296212f35824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namaDok</value>
      <webElementGuid>3188db4d-04b7-4acd-b961-276b92642b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>namaDok</value>
      <webElementGuid>b4e48449-e180-4e62-8522-de246a1d735f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6bc3bfe-d307-4f05-be4a-7c3ff0c8f518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c0e3f33d-83d8-410d-8f0d-cd92ea8ff1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namaDok&quot;)</value>
      <webElementGuid>76dd8e98-dc0b-41e2-85b6-5ac9bb5c3c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namaDok']</value>
      <webElementGuid>4a0a7667-375d-4b80-a4ef-5c9fb40d12a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-4']/jhi-payung-dokpostkontrak-listgw/jhi-payung-dokpostkontrak-formgw/p-dialog/div/div/div[2]/form/div/div[2]/div/div/input</value>
      <webElementGuid>62340ae7-6912-4246-8f75-d4375deb8b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>b3033f45-2759-4f13-8329-3e195a49e4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namaDok' and @type = 'text']</value>
      <webElementGuid>645405c7-b0f5-471f-9498-5afec3356033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
